"""

Revision ID: 08f34ac73fe7
Revises: 1ec0e1a38172
Create Date: 2024-07-10 10:04:42.410953

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '08f34ac73fe7'
down_revision: Union[str, None] = '1ec0e1a38172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'service_token', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_token', type_='unique')
    # ### end Alembic commands ###
