"""update tables

Revision ID: a3432eaa8d36
Revises: e99c79d83019
Create Date: 2024-05-11 10:53:27.303410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3432eaa8d36'
down_revision: Union[str, None] = 'e99c79d83019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('schedule_parsed_at', sa.DateTime(), nullable=True))
    op.add_column('group_lesson', sa.Column('parsed_dates_status', sa.String(), nullable=True))
    op.drop_column('group_lesson', 'parsed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_lesson', sa.Column('parsed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('group_lesson', 'parsed_dates_status')
    op.drop_column('group', 'schedule_parsed_at')
    # ### end Alembic commands ###
