"""Remove department from teacher

Revision ID: d1e891198dd4
Revises: e635d6f719e5
Create Date: 2024-07-15 10:58:14.917494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e891198dd4'
down_revision: Union[str, None] = 'e635d6f719e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'student',
        'group_id',
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_constraint('teacher_department_id_fkey', 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'teacher',
        sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        'teacher_department_id_fkey',
        'teacher',
        'department',
        ['department_id'],
        ['id'],
    )
    op.alter_column(
        'student',
        'group_id',
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
