"""fix typo in teacher model

Revision ID: e99c79d83019
Revises: 3a5299e32409
Create Date: 2024-05-10 16:42:56.170865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99c79d83019'
down_revision: Union[str, None] = '3a5299e32409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('department_id', sa.Uuid(), nullable=False))
    op.drop_constraint('teacher_departament_id_fkey', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'department', ['department_id'], ['id'])
    op.drop_column('teacher', 'departament_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'teacher',
        sa.Column('departament_id', sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key(
        'teacher_departament_id_fkey',
        'teacher',
        'department',
        ['departament_id'],
        ['id'],
    )
    op.drop_column('teacher', 'department_id')
    # ### end Alembic commands ###
