services:
  pocket_kai_api:
    container_name: pocket_kai_fastapi
    build:
      dockerfile: docker/Dockerfile
      context: ./pocket_kai_api_service
      target: production
    ports:
      - "8001:80"
    restart: unless-stopped
    env_file:
      - ./pocket_kai_api_service/.env
    depends_on:
      - pocket_kai_postgres
      - kai_parser_api

  kai_parser_api:
    container_name: kai_parser_fastapi
    build:
      dockerfile: docker/Dockerfile
      context: ./kai_parser_service
      target: production
    ports:
      - "8002:80"
    restart: unless-stopped

  database_updater_service:
    container_name: database_updater
    build:
      dockerfile: docker/Dockerfile
      context: ./database_updater_service
    restart: unless-stopped
    env_file:
      - ./database_updater_service/.env
    depends_on:
      - pocket_kai_api
      - kai_parser_api

  pocket_kai_postgres:
    image: postgres:16-alpine
    container_name: pocket_kai_postgres
    restart: unless-stopped
    env_file:
      - ./pocket_kai_api_service/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
