services:
  kai_parser_api:
    container_name: kai_parser_fastapi
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: development
    ports:
      - "8002:8000"
    restart: unless-stopped
    volumes:
      - ../:/app/
