"""Update group model

Revision ID: 1be16526ac45
Revises: 95fb3ec41020
Create Date: 2024-07-29 10:09:54.582949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be16526ac45'
down_revision: Union[str, None] = '95fb3ec41020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('exams_parsed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'exams_parsed_at')
    # ### end Alembic commands ###
