"""Department can be NULL

Revision ID: 1ec0e1a38172
Revises: a3432eaa8d36
Create Date: 2024-05-19 13:08:24.336277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ec0e1a38172'
down_revision: Union[str, None] = 'a3432eaa8d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'group_lesson',
        'start_time',
        existing_type=postgresql.TIME(),
        nullable=True,
    )
    op.alter_column(
        'group_lesson',
        'department_id',
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        'teacher',
        'department_id',
        existing_type=sa.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'teacher',
        'department_id',
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        'group_lesson',
        'department_id',
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        'group_lesson',
        'start_time',
        existing_type=postgresql.TIME(),
        nullable=False,
    )
    # ### end Alembic commands ###
