"""add service_token

Revision ID: 3a5299e32409
Revises: 1353a33ea79b
Create Date: 2024-05-10 16:14:00.022771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5299e32409'
down_revision: Union[str, None] = '1353a33ea79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'service_token',
        sa.Column('token', sa.String(), nullable=False),
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('group_lesson', sa.Column('department_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'group_lesson', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_lesson', type_='foreignkey')
    op.drop_column('group_lesson', 'department_id')
    op.drop_table('service_token')
    # ### end Alembic commands ###
