"""Add exam

Revision ID: 95fb3ec41020
Revises: d1e891198dd4
Create Date: 2024-07-27 16:00:21.640967

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fb3ec41020'
down_revision: Union[str, None] = 'd1e891198dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'exam',
        sa.Column('original_date', sa.String(), nullable=False),
        sa.Column('time', sa.Time(), nullable=False),
        sa.Column('audience_number', sa.String(), nullable=True),
        sa.Column('building_number', sa.String(), nullable=True),
        sa.Column('parsed_date', sa.Date(), nullable=True),
        sa.Column('academic_year', sa.String(), nullable=False),
        sa.Column('academic_year_half', sa.Integer(), nullable=False),
        sa.Column('semester', sa.Integer(), nullable=True),
        sa.Column('discipline_id', sa.Uuid(), nullable=False),
        sa.Column('teacher_id', sa.Uuid(), nullable=True),
        sa.Column('group_id', sa.Uuid(), nullable=False),
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id']),
        sa.ForeignKeyConstraint(['group_id'], ['group.id']),
        sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam')
    # ### end Alembic commands ###
