"""Fix kai user model

Revision ID: b13615cb75b1
Revises: 9243bc42daa6
Create Date: 2024-07-12 15:29:54.060779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13615cb75b1'
down_revision: Union[str, None] = '9243bc42daa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'kai_user',
        'pocket_kai_user_id',
        existing_type=sa.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'kai_user',
        'pocket_kai_user_id',
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
