services:
  pocket_kai_api:
    container_name: pocket_kai_fastapi
    build: .
    ports:
      - "8001:8000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - pocket_kai_postgres
    volumes:
      - ./:/app/

  pocket_kai_postgres:
    image: postgres:16-alpine
    container_name: pocket_kai_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
