from .group import Group
from .group_lesson import GroupLesson
from .institute import Institute
from .profile import Profile
from .department import Departament
from .speciality import Speciality
from .user import KAIUser
from .teacher import Teacher
from .discipline import Discipline
