"""Update

Revision ID: eefa1b67241e
Revises: e222fbf28514
Create Date: 2024-04-27 11:59:38.142211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefa1b67241e'
down_revision: Union[str, None] = 'e222fbf28514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('syllabus_url', sa.String(), nullable=True))
    op.add_column('group', sa.Column('educational_program_url', sa.String(), nullable=True))
    op.add_column('group', sa.Column('study_schedule_url', sa.String(), nullable=True))
    op.drop_column('group', 'educational_program')
    op.drop_column('group', 'study_schedule')
    op.drop_column('group', 'syllabus')
    op.drop_constraint('teacher_kai_id_key', 'teacher', type_='unique')
    op.drop_column('teacher', 'kai_id')
    op.alter_column('token', 'token',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'token', 'pocket_kai_user', ['pocket_kai_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.alter_column('token', 'token',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('teacher', sa.Column('kai_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('teacher_kai_id_key', 'teacher', ['kai_id'])
    op.add_column('group', sa.Column('syllabus', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('study_schedule', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('educational_program', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('group', 'study_schedule_url')
    op.drop_column('group', 'educational_program_url')
    op.drop_column('group', 'syllabus_url')
    # ### end Alembic commands ###
